### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by wangjian27** [sulgweb/sulg-plugin-cli#1]
* mac使用sulgPlugin的时候报错"env: node\r: No such file or directory"
* 将全局根目录下的node_modules中sulgPlugin由原来CRLF改为LF格式即可解决报错
* 保存的时候以LF格式保存，具体可参考这篇文章https://zhuanlan.zhihu.com/p/361710559

**Comment by sulgweb** [comment]
感谢提醒，1.0.6版本已修复~
